name: Check NBA Update

on:
  schedule:
    # 1 a.m. New York time (06:00 UTC)
    - cron: '0 6 * * *'
    # 1 a.m. California time (08:00 UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:  # allows you to run manually from the Actions tab

jobs:
  check-nba-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run NBA update check
        run: |
          python check_nba_update.py

      - name: Commit updated state file (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add nba_last_update.txt
          git diff --quiet && echo "No change to commit" || git commit -m "NBA update check: $(date)"
          git push
